/* unit-imx8qm-flexspi-write.c
 *
 * Locks down the FlexSPI0 serial-NOR driver in hal/imx8qm.c: the page-boundary
 * split and per-page Write Enable in ext_flash_write(), and the sector
 * rounding in ext_flash_erase().
 *
 * Both are classic NOR bugs that a build cannot catch and that look like
 * intermittent corruption on hardware:
 *
 *  - A NOR page program that crosses a page boundary does not continue into
 *    the next page; the device's write pointer wraps to the start of the
 *    current page and the excess bytes overwrite what was just written.
 *  - NOR clears its write-enable latch after every program and every erase, so
 *    a single Write Enable up front leaves every operation after the first
 *    silently dropped while the driver still reports success. This is the exact
 *    bug unit-ls1028a-xspi-write was written for, on the driver this one was
 *    ported from.
 *
 * The driver is extracted verbatim from hal/imx8qm.c (imx8qm_flexspi_extract.h,
 * generated by the Makefile) and driven against an emulated FlexSPI controller
 * and NOR device. The emulated device keeps a real write-enable latch, a busy
 * (WIP) window and true NOR program semantics - a program can only clear bits,
 * never set them - so a dropped Write Enable or a wrapped page shows up as
 * wrong data rather than being quietly accepted.
 *
 * Copyright (C) 2026 wolfSSL Inc.
 *
 * This file is part of wolfBoot.
 *
 * wolfBoot is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfBoot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 */

#include <check.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define TARGET_imx8qm
#define ARCH_AARCH64
#define EXT_FLASH

#include "imx8qm.h"

/* Emulated controller register block and NOR array, in place of 0x5D120000
 * and the AHB window at 0x08000000. The device is shrunk from 64 MB to 512 KB
 * (four erase sectors):
 * the bounds checks are relative to IMX8QM_FLEXSPI0_SIZE, so they keep their
 * meaning while the array stays a sensible size for a host test. */
static uint32_t g_fspi[0x400];
static uint8_t  g_nor[0x80000];   /* 4 x 128 KiB sectors */

#undef IMX8QM_FLEXSPI0_BASE
#define IMX8QM_FLEXSPI0_BASE     ((uintptr_t)g_fspi)
#undef IMX8QM_FLEXSPI0_AHB_BASE
#define IMX8QM_FLEXSPI0_AHB_BASE ((uintptr_t)g_nor)
#undef IMX8QM_FLEXSPI0_SIZE
#define IMX8QM_FLEXSPI0_SIZE     ((uint32_t)sizeof(g_nor))

#define FREG(off) g_fspi[(off) / 4]

/* --- Emulated NOR device --------------------------------------------------
 * Modelled at the IP-command trigger, the same boundary
 * unit-ls1028a-xspi-write uses. */

enum { OP_READ, OP_WREN, OP_RDSR, OP_SE, OP_PP };

#define LOG_MAX 128
static struct { int op; uint32_t addr; uint32_t len; } g_log[LOG_MAX];
static int g_log_n;

static int      g_wel;          /* write-enable latch */
static int      g_wip;          /* program/erase in progress */
static int      g_rejects;      /* operations refused for a missing WEL */
static uint8_t  g_txfifo[256];
static uint32_t g_tx_n;

static void nor_log(int op, uint32_t addr, uint32_t len)
{
    if (g_log_n < LOG_MAX) {
        g_log[g_log_n].op = op;
        g_log[g_log_n].addr = addr;
        g_log[g_log_n].len = len;
        g_log_n++;
    }
}

static void nor_exec(uint32_t seq, uint32_t addr, uint32_t len)
{
    uint32_t i;

    switch (seq) {
    case FLEXSPI_LUT_SEQ_WREN:
        g_wel = 1;
        nor_log(OP_WREN, addr, 0);
        break;

    case FLEXSPI_LUT_SEQ_RDSR:
        nor_log(OP_RDSR, addr, len);
        /* The busy window closes on the second poll, so a driver that never
         * waits and one that waits correctly behave differently. */
        FREG(FLEXSPI_RFDR0) = g_wip ? FLEXSPI_NOR_SR_WIP : 0;
        if (g_wip)
            g_wip--;
        break;

    case FLEXSPI_LUT_SEQ_SE:
        nor_log(OP_SE, addr, FLEXSPI_NOR_SECTOR_SIZE);
        if (!g_wel) { g_rejects++; break; }
        if (addr + FLEXSPI_NOR_SECTOR_SIZE <= sizeof(g_nor))
            memset(&g_nor[addr], 0xFF, FLEXSPI_NOR_SECTOR_SIZE);
        g_wel = 0;              /* the latch clears after the operation */
        g_wip = 2;
        break;

    case FLEXSPI_LUT_SEQ_PP:
        nor_log(OP_PP, addr, len);
        if (!g_wel) { g_rejects++; break; }
        /* Real NOR semantics: a program can only clear bits, and the write
         * pointer wraps within the page rather than running into the next
         * one. Both make a driver bug visible as wrong data. */
        for (i = 0; i < len && i < g_tx_n; i++) {
            uint32_t page = addr & ~(FLEXSPI_NOR_PAGE_SIZE - 1);
            uint32_t off  = page +
                ((addr - page + i) % FLEXSPI_NOR_PAGE_SIZE);
            if (off < sizeof(g_nor))
                g_nor[off] &= g_txfifo[i];
        }
        g_wel = 0;
        g_wip = 2;
        break;

    default:
        nor_log(OP_READ, addr, len);
        break;
    }
    g_tx_n = 0;
    FREG(FLEXSPI_INTR) |= FLEXSPI_INTR_IPCMDDONE;
}

static inline uint32_t rd32(uintptr_t a)
{
    return *(volatile uint32_t*)a;
}

static void wr32(uintptr_t a, uint32_t v)
{
    uint32_t off = (uint32_t)(a - (uintptr_t)g_fspi);
    uint32_t i;

    /* The TX FIFO is drained into a staging buffer each time the driver
     * acknowledges the watermark, then programmed when the command runs. */
    if (off == FLEXSPI_INTR && (v & FLEXSPI_INTR_IPTXWE) != 0) {
        for (i = 0; i < FLEXSPI_IP_WM_BYTES && g_tx_n < sizeof(g_txfifo); i++)
            g_txfifo[g_tx_n++] =
                ((const uint8_t*)&g_fspi[FLEXSPI_TFDR0 / 4])[i];
        /* Write-1-to-clear, and keep the watermark asserted for the next
         * burst. */
        FREG(FLEXSPI_INTR) &= ~v;
        FREG(FLEXSPI_INTR) |= FLEXSPI_INTR_IPTXWE;
        return;
    }
    if (off == FLEXSPI_INTR) {           /* other write-1-to-clear bits */
        FREG(FLEXSPI_INTR) &= ~v;
        FREG(FLEXSPI_INTR) |= FLEXSPI_INTR_IPTXWE;
        return;
    }

    *(volatile uint32_t*)a = v;

    if (off == FLEXSPI_MCR0 && (v & FLEXSPI_MCR0_SWRESET) != 0)
        FREG(FLEXSPI_MCR0) &= ~(uint32_t)FLEXSPI_MCR0_SWRESET; /* self-clears */

    if (off == FLEXSPI_IPCMD && (v & FLEXSPI_IPCMD_TRG) != 0) {
        nor_exec((FREG(FLEXSPI_IPCR1) >> 16) & 0xFFFF,
                 FREG(FLEXSPI_IPCR0),
                 FREG(FLEXSPI_IPCR1) & 0xFFFF);
    }
}

/* Reset the tick count per deadline, as unit-imx8qm-usdhc-shim.c does.
 * Accumulating across every deadline in a test makes a later timeout depend on
 * how many times earlier operations polled, so adding a poll anywhere in the
 * driver could trip an unrelated wait. */
static int g_ticks;
static uint64_t timer_deadline_us(uint32_t us) { (void)us; g_ticks = 0; return 0; }
static int timer_expired(uint64_t d) { (void)d; return ++g_ticks > 100000; }

static int g_printf_calls;
#define wolfBoot_printf(...) do { g_printf_calls++; } while (0)

#include "imx8qm_flexspi_extract.h"

#undef wolfBoot_printf

static void setup(void)
{
    memset(g_fspi, 0, sizeof(g_fspi));
    memset(g_nor, 0xFF, sizeof(g_nor));
    g_log_n = 0;
    g_wel = 0;
    g_wip = 0;
    g_rejects = 0;
    g_tx_n = 0;
    g_ticks = 0;
    g_printf_calls = 0;
    flexspi_ready = 0;
    FREG(FLEXSPI_INTR) = FLEXSPI_INTR_IPTXWE;
}

static void teardown(void) { }

static int count_op(int op)
{
    int i, n = 0;
    for (i = 0; i < g_log_n; i++)
        if (g_log[i].op == op)
            n++;
    return n;
}

/* Index of the n-th (0-based) occurrence of an operation in the log, or -1.
 * Status polls sit between the programs, so the log positions are not fixed. */
static int nth_op(int op, int n)
{
    int i;
    for (i = 0; i < g_log_n; i++) {
        if (g_log[i].op == op && n-- == 0)
            return i;
    }
    return -1;
}

/* Every program and erase must be immediately preceded by its own Write
 * Enable. */
static int every_op_has_wren(int op)
{
    int i;
    for (i = 0; i < g_log_n; i++) {
        if (g_log[i].op != op)
            continue;
        if (i == 0 || g_log[i - 1].op != OP_WREN)
            return 0;
    }
    return 1;
}

/* --------------------------------------------------------------------------
 * Page programming
 * -------------------------------------------------------------------------- */

START_TEST(test_write_single_page)
{
    uint8_t buf[64];
    int i;

    for (i = 0; i < (int)sizeof(buf); i++)
        buf[i] = (uint8_t)(i + 1);

    ck_assert_int_eq(ext_flash_write(0x1000, buf, sizeof(buf)),
                     (int)sizeof(buf));
    ck_assert_int_eq(count_op(OP_PP), 1);
    ck_assert_int_eq(g_rejects, 0);
    ck_assert_int_eq(memcmp(&g_nor[0x1000], buf, sizeof(buf)), 0);
}
END_TEST

/* Two full pages: two programs, each with its own Write Enable. A single
 * up-front WEN leaves the second page unwritten. */
START_TEST(test_write_two_pages_each_write_enabled)
{
    uint8_t buf[512];
    int i;

    for (i = 0; i < (int)sizeof(buf); i++)
        buf[i] = (uint8_t)(i & 0xFF) ^ 0xA5;

    ck_assert_int_eq(ext_flash_write(0, buf, sizeof(buf)), (int)sizeof(buf));
    ck_assert_int_eq(count_op(OP_PP), 2);
    ck_assert_int_eq(count_op(OP_WREN), 2);
    ck_assert(every_op_has_wren(OP_PP));
    ck_assert_int_eq(g_rejects, 0);
    ck_assert_int_eq(memcmp(g_nor, buf, sizeof(buf)), 0);
}
END_TEST

/* A write starting mid-page must be capped at the bytes left in that page.
 * Without the cap the device wraps and corrupts the start of the page. */
START_TEST(test_write_crossing_page_boundary)
{
    uint8_t buf[100];
    int i;

    for (i = 0; i < (int)sizeof(buf); i++)
        buf[i] = (uint8_t)(0xC0 | (i & 0x0F));

    /* 16 bytes left in the first page, 84 into the next. */
    ck_assert_int_eq(ext_flash_write(0xF0, buf, sizeof(buf)),
                     (int)sizeof(buf));
    ck_assert_int_eq(count_op(OP_PP), 2);
    ck_assert_uint_eq(g_log[nth_op(OP_PP, 0)].addr, 0xF0);
    ck_assert_uint_eq(g_log[nth_op(OP_PP, 0)].len, 16);
    ck_assert_uint_eq(g_log[nth_op(OP_PP, 1)].addr, 0x100);
    ck_assert_uint_eq(g_log[nth_op(OP_PP, 1)].len, 84);
    ck_assert_int_eq(memcmp(&g_nor[0xF0], buf, sizeof(buf)), 0);
}
END_TEST

/* A length that is not a multiple of the FIFO watermark must still land
 * exactly, with no trailing bytes from the previous burst. */
START_TEST(test_write_unaligned_length)
{
    uint8_t buf[13];
    int i;

    for (i = 0; i < (int)sizeof(buf); i++)
        buf[i] = (uint8_t)(0x10 + i);

    ck_assert_int_eq(ext_flash_write(0x40, buf, sizeof(buf)),
                     (int)sizeof(buf));
    ck_assert_int_eq(memcmp(&g_nor[0x40], buf, sizeof(buf)), 0);
    /* Nothing outside the requested range may be touched. */
    ck_assert_uint_eq(g_nor[0x40 - 1], 0xFF);
    ck_assert_uint_eq(g_nor[0x40 + sizeof(buf)], 0xFF);
}
END_TEST

/* The driver must wait out the busy window before the next Write Enable: NOR
 * ignores WEN while a program is still running. */
START_TEST(test_write_waits_for_wip)
{
    uint8_t buf[512];

    memset(buf, 0x5A, sizeof(buf));
    ck_assert_int_eq(ext_flash_write(0, buf, sizeof(buf)), (int)sizeof(buf));
    /* At least one status poll per program. */
    ck_assert_int_ge(count_op(OP_RDSR), 2);
    ck_assert_int_eq(g_rejects, 0);
}
END_TEST

START_TEST(test_write_rejects_out_of_range)
{
    uint8_t buf[4] = { 1, 2, 3, 4 };

    ck_assert_int_eq(ext_flash_write(IMX8QM_FLEXSPI0_SIZE - 2, buf, 4), -1);
    ck_assert_int_eq(count_op(OP_PP), 0);
}
END_TEST

/* --------------------------------------------------------------------------
 * Erase
 * -------------------------------------------------------------------------- */

START_TEST(test_erase_rounds_down_to_sector)
{
    memset(g_nor, 0x00, sizeof(g_nor));

    /* One byte in the middle of a sector still erases that whole sector. */
    ck_assert_int_eq(ext_flash_erase(FLEXSPI_NOR_SECTOR_SIZE + 0x800, 1), 1);
    ck_assert_int_eq(count_op(OP_SE), 1);
    ck_assert_uint_eq(g_log[nth_op(OP_SE, 0)].addr, FLEXSPI_NOR_SECTOR_SIZE);
    ck_assert_uint_eq(g_nor[FLEXSPI_NOR_SECTOR_SIZE], 0xFF);
    ck_assert_uint_eq(g_nor[2 * FLEXSPI_NOR_SECTOR_SIZE - 1], 0xFF);
    /* Neighbouring sectors are untouched. */
    ck_assert_uint_eq(g_nor[FLEXSPI_NOR_SECTOR_SIZE - 1], 0x00);
    ck_assert_uint_eq(g_nor[2 * FLEXSPI_NOR_SECTOR_SIZE], 0x00);
}
END_TEST

/* A range that straddles a sector boundary must erase both sectors - the
 * partial head as well as the tail. */
START_TEST(test_erase_spanning_two_sectors)
{
    memset(g_nor, 0x00, sizeof(g_nor));

    ck_assert_int_eq(ext_flash_erase(FLEXSPI_NOR_SECTOR_SIZE - 1, 2), 2);
    ck_assert_int_eq(count_op(OP_SE), 2);
    ck_assert_uint_eq(g_nor[0x0000], 0xFF);
    ck_assert_uint_eq(g_nor[2 * FLEXSPI_NOR_SECTOR_SIZE - 1], 0xFF);
    ck_assert_uint_eq(g_nor[2 * FLEXSPI_NOR_SECTOR_SIZE], 0x00);
}
END_TEST

START_TEST(test_erase_write_enables_each_sector)
{
    memset(g_nor, 0x00, sizeof(g_nor));

    ck_assert_int_eq(ext_flash_erase(0, (int)sizeof(g_nor)),
                     (int)sizeof(g_nor));
    ck_assert_int_eq(count_op(OP_SE), 4);
    ck_assert_int_eq(count_op(OP_WREN), 4);
    ck_assert(every_op_has_wren(OP_SE));
    ck_assert_int_eq(g_rejects, 0);
}
END_TEST

START_TEST(test_erase_rejects_out_of_range)
{
    ck_assert_int_eq(ext_flash_erase(IMX8QM_FLEXSPI0_SIZE, 4), -1);
    ck_assert_int_eq(ext_flash_erase(0, 0), -1);
    ck_assert_int_eq(count_op(OP_SE), 0);
}
END_TEST

/* --------------------------------------------------------------------------
 * Read and LUT setup
 * -------------------------------------------------------------------------- */

/* Reads come from the memory-mapped window. Both a device offset and a full
 * AHB address must work, because wolfBoot partition addresses are the latter. */
START_TEST(test_read_accepts_both_address_forms)
{
    uint8_t out[16];

    memset(&g_nor[0x800], 0x3C, sizeof(out));

    ck_assert_int_eq(ext_flash_read(0x800, out, sizeof(out)), (int)sizeof(out));
    ck_assert_uint_eq(out[0], 0x3C);

    memset(out, 0, sizeof(out));
    ck_assert_int_eq(ext_flash_read(IMX8QM_FLEXSPI0_AHB_BASE + 0x800, out,
                                    sizeof(out)), (int)sizeof(out));
    ck_assert_uint_eq(out[0], 0x3C);
}
END_TEST

START_TEST(test_read_rejects_out_of_range)
{
    uint8_t out[8];
    ck_assert_int_eq(ext_flash_read(IMX8QM_FLEXSPI0_SIZE - 4, out, 8), -1);
}
END_TEST

/* The LUT must be programmed with 4-byte-address opcodes: the part is past the
 * 16 MB limit of 3-byte addressing, so a 3-byte sequence would silently alias
 * every access into the low 16 MB. */
START_TEST(test_lut_programmed_with_4byte_opcodes)
{
    ext_flash_unlock();     /* triggers flexspi_init() */

    ck_assert_uint_eq(FREG(FLEXSPI_LUT0 + FLEXSPI_LUT_SEQ_READ * 16) & 0xFF,
                      FLEXSPI_NOR_CMD_READ_4B);
    ck_assert_uint_eq(FREG(FLEXSPI_LUT0 + FLEXSPI_LUT_SEQ_WREN * 16) & 0xFF,
                      FLEXSPI_NOR_CMD_WREN);
    ck_assert_uint_eq(FREG(FLEXSPI_LUT0 + FLEXSPI_LUT_SEQ_RDSR * 16) & 0xFF,
                      FLEXSPI_NOR_CMD_RDSR);
    ck_assert_uint_eq(FREG(FLEXSPI_LUT0 + FLEXSPI_LUT_SEQ_SE * 16) & 0xFF,
                      FLEXSPI_NOR_CMD_SE_4B);
    ck_assert_uint_eq(FREG(FLEXSPI_LUT0 + FLEXSPI_LUT_SEQ_PP * 16) & 0xFF,
                      FLEXSPI_NOR_CMD_PP_4B);

    /* 32-bit address phase on the sequences that take an address. */
    ck_assert_uint_eq((FREG(FLEXSPI_LUT0 + FLEXSPI_LUT_SEQ_READ * 16) >> 16)
                      & 0xFF, 32);
    ck_assert_uint_eq((FREG(FLEXSPI_LUT0 + FLEXSPI_LUT_SEQ_SE * 16) >> 16)
                      & 0xFF, 32);

    /* AHB reads have to point at the READ sequence, and only flash A1 is
     * populated on this board. */
    ck_assert_uint_eq(FREG(FLEXSPI_FLSHA1CR2), FLEXSPI_LUT_SEQ_READ);
    ck_assert_uint_eq(FREG(FLEXSPI_FLSHA1CR0), IMX8QM_FLEXSPI0_SIZE / 1024);
}
END_TEST

Suite *imx8qm_flexspi_suite(void)
{
    Suite *s = suite_create("imx8qm-flexspi-write");
    TCase *tc = tcase_create("imx8qm-flexspi-write");

    tcase_add_checked_fixture(tc, setup, teardown);
    tcase_add_test(tc, test_write_single_page);
    tcase_add_test(tc, test_write_two_pages_each_write_enabled);
    tcase_add_test(tc, test_write_crossing_page_boundary);
    tcase_add_test(tc, test_write_unaligned_length);
    tcase_add_test(tc, test_write_waits_for_wip);
    tcase_add_test(tc, test_write_rejects_out_of_range);
    tcase_add_test(tc, test_erase_rounds_down_to_sector);
    tcase_add_test(tc, test_erase_spanning_two_sectors);
    tcase_add_test(tc, test_erase_write_enables_each_sector);
    tcase_add_test(tc, test_erase_rejects_out_of_range);
    tcase_add_test(tc, test_read_accepts_both_address_forms);
    tcase_add_test(tc, test_read_rejects_out_of_range);
    tcase_add_test(tc, test_lut_programmed_with_4byte_opcodes);

    suite_add_tcase(s, tc);
    return s;
}

int main(void)
{
    int fails;
    Suite *s = imx8qm_flexspi_suite();
    SRunner *sr = srunner_create(s);

    srunner_run_all(sr, CK_NORMAL);
    fails = srunner_ntests_failed(sr);
    srunner_free(sr);

    return fails;
}
