/* unit-sdhci-uhs-recover.c
 *
 * Regression test for F-9735: disk_read() called sdhci_uhs_recover()
 * after any nonzero status from a data transfer, which permanently
 * switched the host to 1.8V signaling (SDHCI_SRS15_V18SE) on a plain
 * 3.3V cold boot whenever the first transfer failed for any reason
 * (CRC, DMA, media, controller). If the retry also failed, the voltage
 * setting was never rolled back and g_uhs_recovered prevented further
 * recovery - so a transient error left the host with a signaling level
 * the card is not using, for the rest of the boot and the stage that
 * follows it.
 *
 * The test compiles the real src/sdhci.c (as sdhci_host.c, generated by
 * the Makefile). The generated copy differs from the real file only in:
 *   - three `asm volatile` barrier/nop statements blanked (cannot
 *     assemble on x86);
 *   - the real sdhci_read() renamed to sdhci_read_hw() so this file can
 *     provide a scripted sdhci_read() that stands in for the command /
 *     data-transfer state machine.
 * Register access goes through the platform-provided sdhci_reg_read()/
 * sdhci_reg_write(), backed here by a host register array, so the test
 * asserts directly on the SDHCI_SRS15 / SDHCI_SRS11 state.
 *
 * Copyright (C) 2026 wolfSSL Inc.
 *
 * This file is part of wolfBoot.
 *
 * wolfBoot is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfBoot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 */

#include <check.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdarg.h>

#include "sdhci.h"
#include "disk.h"

/* Host register file for the platform-provided register accessors. */
static uint32_t g_sdhci_regs[0x400 / sizeof(uint32_t)];

uint32_t sdhci_reg_read(uint32_t offset)
{
    return g_sdhci_regs[offset / sizeof(uint32_t)];
}

void sdhci_reg_write(uint32_t offset, uint32_t val)
{
    g_sdhci_regs[offset / sizeof(uint32_t)] = val;
}

/* Timer for udelay(): advance on every read so busy loops terminate. */
static uint64_t g_timer_us;
uint64_t hal_get_timer_us(void)
{
    return ++g_timer_us;
}

void wolfBoot_printf(const char *format, ...)
{
    (void)format;
}

/* Platform hooks the SD init path touches; irrelevant to the recovery
 * logic under test. */
void sdhci_platform_init(void)
{
}

void sdhci_platform_irq_init(void)
{
}

void sdhci_platform_set_bus_mode(int is_emmc)
{
    (void)is_emmc;
}

/* Scripted sdhci_read(): plays back g_read_script one entry per call.
 * 0 = success (fills dst with a per-block pattern), nonzero = failure. */
#define MAX_READ_CALLS 32
static int g_read_script[MAX_READ_CALLS];
static int g_read_calls;
static int g_script_len;

int sdhci_read(uint32_t cmd_index, uint32_t block_addr, uint32_t *dst,
    uint32_t sz)
{
    int ret;
    uint32_t i;

    (void)cmd_index;
    if (g_read_calls >= g_script_len)
        return -1;
    ret = g_read_script[g_read_calls];
    g_read_calls++;
    if (ret == 0) {
        for (i = 0; i < sz / sizeof(uint32_t); i++)
            dst[i] = (uint32_t)(0xA5 + block_addr + i);
    }
    return ret;
}

/* The real HAL (identical to src/sdhci.c apart from the transforms
 * documented above). */
#include "sdhci_host.c"

static void setup(void)
{
    memset(g_sdhci_regs, 0, sizeof(g_sdhci_regs));
    g_timer_us = 0;
    g_read_calls = 0;
    g_script_len = 0;
}

static void teardown(void)
{
}

static void script(const int *vals, int n)
{
    if (n > MAX_READ_CALLS)
        n = MAX_READ_CALLS;
    memcpy(g_read_script, vals, (size_t)n * sizeof(int));
    g_script_len = n;
    g_read_calls = 0; /* a new script starts from its first entry */
}

/* A clean read must not touch the signaling level at all. */
START_TEST(test_clean_read_no_switch)
{
    static uint8_t __attribute__((aligned(4))) buf[SDHCI_BLOCK_SIZE];

    script((int[]){ 0 }, 1);
    ck_assert_int_eq(disk_read(0, 0, sizeof(buf), buf), 0);
    ck_assert_int_eq(g_sdhci_regs[SDHCI_SRS15 / 4] & SDHCI_SRS15_V18SE, 0);
}
END_TEST

/* First transfer fails, the 1.8V retry succeeds: the switch stays (the
 * card really was left in UHS-I by a previous stage). */
START_TEST(test_retry_success_keeps_switch)
{
    static uint8_t __attribute__((aligned(4))) buf[SDHCI_BLOCK_SIZE];

    script((int[]){ -1, 0 }, 2);
    ck_assert_int_eq(disk_read(0, 0, sizeof(buf), buf), 0);
    ck_assert_int_eq(g_sdhci_regs[SDHCI_SRS15 / 4] & SDHCI_SRS15_V18SE,
        SDHCI_SRS15_V18SE);
    ck_assert_int_eq(g_sdhci_regs[SDHCI_SRS11 / 4] & SDHCI_SRS11_SDCE,
        SDHCI_SRS11_SDCE);
    ck_assert_uint_eq(buf[0], 0xA5);
}
END_TEST

/* First transfer fails and the 1.8V retry fails too: this is not a
 * warm-reset UHS condition - restore 3.3V signaling and the clock so
 * the host is not left in a state the card is not using. */
START_TEST(test_retry_failure_rolls_back)
{
    static uint8_t __attribute__((aligned(4))) buf[SDHCI_BLOCK_SIZE];

    script((int[]){ -1, -1 }, 2);
    ck_assert_int_eq(disk_read(0, 0, sizeof(buf), buf), -1);
    ck_assert_int_eq(g_sdhci_regs[SDHCI_SRS15 / 4] & SDHCI_SRS15_V18SE, 0);
    ck_assert_int_eq(g_sdhci_regs[SDHCI_SRS11 / 4] & SDHCI_SRS11_SDCE,
        SDHCI_SRS11_SDCE);
}
END_TEST

/* A later read fails after a recovery that is actually working: the
 * 1.8V configuration must be kept (rolling it back would break a card
 * that is really at 1.8V). Two disk_read() calls because the upper
 * layer reads in chunks. */
START_TEST(test_later_failure_keeps_working_switch)
{
    static uint8_t __attribute__((aligned(4))) buf1[SDHCI_BLOCK_SIZE];
    static uint8_t __attribute__((aligned(4))) buf2[SDHCI_BLOCK_SIZE];

    /* chunk 1: first attempt fails, 1.8V retry works */
    script((int[]){ -1, 0 }, 2);
    ck_assert_int_eq(disk_read(0, 0, sizeof(buf1), buf1), 0);
    ck_assert_int_eq(g_sdhci_regs[SDHCI_SRS15 / 4] & SDHCI_SRS15_V18SE,
        SDHCI_SRS15_V18SE);

    /* chunk 2: a later, unrelated failure - the working 1.8V config
     * must stay */
    script((int[]){ -1 }, 1);
    ck_assert_int_eq(disk_read(0, SDHCI_BLOCK_SIZE, sizeof(buf2), buf2),
        -1);
    ck_assert_int_eq(g_sdhci_regs[SDHCI_SRS15 / 4] & SDHCI_SRS15_V18SE,
        SDHCI_SRS15_V18SE);
}
END_TEST

/* After a rollback the recovery must be available again. The host is
 * back at 3.3V, so leaving the one-shot spent would strand a genuinely
 * UHS-I card at the wrong signaling level for the rest of the boot --
 * a state the code before the rollback existed could not reach. */
START_TEST(test_rollback_allows_later_retry)
{
    static uint8_t __attribute__((aligned(4))) buf1[SDHCI_BLOCK_SIZE];
    static uint8_t __attribute__((aligned(4))) buf2[SDHCI_BLOCK_SIZE];

    /* first read: both attempts fail, so the switch is rolled back */
    script((int[]){ -1, -1 }, 2);
    ck_assert_int_eq(disk_read(0, 0, sizeof(buf1), buf1), -1);
    ck_assert_int_eq(g_sdhci_regs[SDHCI_SRS15 / 4] & SDHCI_SRS15_V18SE, 0);

    /* second read: the 1.8V retry must be attempted again, and works */
    script((int[]){ -1, 0 }, 2);
    ck_assert_int_eq(disk_read(0, SDHCI_BLOCK_SIZE, sizeof(buf2), buf2), 0);
    ck_assert_int_eq(g_sdhci_regs[SDHCI_SRS15 / 4] & SDHCI_SRS15_V18SE,
        SDHCI_SRS15_V18SE);
}
END_TEST

Suite *sdhci_uhs_suite(void)
{
    Suite *s = suite_create("sdhci-uhs-recover");
    TCase *tc = tcase_create("sdhci-uhs-recover");

    tcase_add_checked_fixture(tc, setup, teardown);
    tcase_add_test(tc, test_clean_read_no_switch);
    tcase_add_test(tc, test_retry_success_keeps_switch);
    tcase_add_test(tc, test_retry_failure_rolls_back);
    tcase_add_test(tc, test_later_failure_keeps_working_switch);
    tcase_add_test(tc, test_rollback_allows_later_retry);

    suite_add_tcase(s, tc);
    return s;
}

int main(void)
{
    int fails;
    Suite *s = sdhci_uhs_suite();
    SRunner *sr = srunner_create(s);

    srunner_run_all(sr, CK_NORMAL);
    fails = srunner_ntests_failed(sr);
    srunner_free(sr);

    return fails;
}
