/* unit-p1021-fcm-bytes.c
 *
 * Regression test for F-7975: hal_flash_read_bytes() and
 * hal_flash_write_bytes() in hal/nxp_p1021.c loop on
 * `while (flash_idx < len)`, comparing the FCM buffer index (which
 * hal_flash_set_addr() initializes to the page column, `flash_idx = col`)
 * against the caller's relative byte count. With col != 0:
 *
 * - if len <= col the loop runs zero times, so the page program proceeds
 *   with stale FCM buffer contents (write) or the caller's buffer is left
 *   unchanged (read);
 * - if len > col only len - col bytes are copied;
 * - a final one-to-three byte remainder is copied as a full word, reading
 *   or writing outside the requested range.
 *
 * The fix computes an absolute end (flash_idx + len) and copies exactly
 * len bytes, handling the tail byte-wise.
 *
 * hal/nxp_p1021.c is PowerPC code, but the FCM helpers under test are
 * plain byte copies. The test includes the HAL file (via nxp_p1021_host.c,
 * generated by the Makefile) and drives the static helpers directly, with
 * flash_buf backed by a host array standing in for the eLBC FCM region.
 * The host copy differs from the real file only in that the three bare
 * `__asm__ __volatile__("..." )` cache-barrier statements (DDR init and
 * multi-core boot) are blanked out: they cannot assemble on x86. The
 * PowerPC-asm accessors from nxp_ppc.h are shadowed with host versions
 * below, so they are never emitted either.
 *
 * Copyright (C) 2026 wolfSSL Inc.
 *
 * This file is part of wolfBoot.
 *
 * wolfBoot is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfBoot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 */

#include <check.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define TARGET_nxp_p1021

/* Back the CCSR register space with host memory so MMIO-style accesses
 * land somewhere harmless. */
static uint32_t g_ccsr_regs[0x200000 / sizeof(uint32_t)];

#include "nxp_ppc.h"

#undef CCSRBAR
#define CCSRBAR ((uintptr_t)g_ccsr_regs)

/* nxp_ppc.h's memory accessors and SPR helpers are PowerPC asm, which the
 * x86 backend cannot assemble when emitted. The FCM helpers under test
 * need only plain reads/writes, so shadow the asm versions with host
 * equivalents; the asm versions are never referenced from here on and so
 * are never emitted. (nxp_ppc.h is pre-included above, so the HAL's own
 * include of it is a no-op and its register macros expand against the
 * host-backed CCSRBAR.) */
#define get8(addr)  (*(const volatile uint8_t *)(addr))
#define set8(addr, v)  (*(volatile uint8_t *)(addr) = (uint8_t)(v))
#define get16(addr)  (*(const volatile uint16_t *)(addr))
#define set16(addr, v)  (*(volatile uint16_t *)(addr) = (uint16_t)(v))
#define get32(addr)  (*(const volatile uint32_t *)(addr))
#define set32(addr, v)  (*(volatile uint32_t *)(addr) = (uint32_t)(v))
#undef mtspr
#define mtspr(rn, v) ((void)0)
#undef mfspr
#define mfspr(rn) (0)
#undef mfmsr
#define mfmsr() (0)
#undef mtmsr
#define mtmsr(v) ((void)0)

/* PPC runtime symbols referenced by the emitted init code (normally
 * provided by boot_ppc.c / boot_ppc_start.S and the linker script);
 * never called by the tests. */
uint32_t _secondary_start_page;
uint32_t _second_half_boot_page;
uint32_t _bootpg_addr;
uint32_t _spin_table;
uint32_t _spin_table_addr;

unsigned long long get_ticks(void)
{
    return 0;
}
void wait_ticks(unsigned long long t)
{
    (void)t;
}
unsigned long get_pc(void)
{
    return 0;
}
void set_tlb(uint8_t tlb, uint8_t esel, uint32_t epn, uint32_t rpn,
        uint32_t urpn, uint8_t perms, uint8_t wimge, uint8_t ts,
        uint8_t tsize, uint8_t iprot)
{
    (void)tlb; (void)esel; (void)epn; (void)rpn; (void)urpn;
    (void)perms; (void)wimge; (void)ts; (void)tsize; (void)iprot;
}
void disable_tlb1(uint8_t esel)
{
    (void)esel;
}
void flush_cache(uint32_t start_addr, uint32_t size)
{
    (void)start_addr; (void)size;
}
void set_law(uint8_t idx, uint32_t addr_h, uint32_t addr_l,
        uint32_t trgt_id, uint32_t law_sz, int reset)
{
    (void)idx; (void)addr_h; (void)addr_l; (void)trgt_id; (void)law_sz;
    (void)reset;
}

/* Pull in the code under test (its statics become visible here).
 * nxp_p1021_host.c is generated from hal/nxp_p1021.c by the Makefile
 * (see there for the single mechanical difference). */
#include "nxp_p1021_host.c"

/* Host stand-in for the eLBC FCM region (FLASH_BASE_ADDR). */
static uint8_t fcm[1024];

static void setup(void)
{
    memset(fcm, 0x5A, sizeof(fcm));
    flash_buf = (volatile uint8_t *)fcm;
    flash_idx = 0;
}

static void teardown(void)
{
}

/* Fill a data buffer with a deterministic pattern. */
static void fill(uint8_t *buf, size_t len, uint8_t base)
{
    size_t i;

    for (i = 0; i < len; i++)
        buf[i] = (uint8_t)(base + i);
}

/* Column 0 still works: the whole request lands in the FCM buffer. */
START_TEST(test_write_col_zero)
{
    uint8_t data[64];

    fill(data, sizeof(data), 0x11);
    flash_idx = 0;

    hal_flash_write_bytes(data, sizeof(data));

    ck_assert_int_eq(memcmp(fcm, data, sizeof(data)), 0);
    ck_assert_uint_eq(fcm[64], 0x5A);
    ck_assert_uint_eq(flash_idx, 64);
}
END_TEST

/* The core F-7975 case: with col != 0 and len <= col the pre-fix loop
 * ran zero times and the page program went ahead with stale FCM
 * contents. All len bytes must land at FCM offset col. */
START_TEST(test_write_len_le_col)
{
    uint8_t data[50];

    fill(data, sizeof(data), 0x22);
    flash_idx = 100; /* hal_flash_set_addr(page, 100) */

    hal_flash_write_bytes(data, sizeof(data));

    ck_assert_int_eq(memcmp(fcm + 100, data, sizeof(data)), 0);
    ck_assert_uint_eq(fcm[99], 0x5A);
    ck_assert_uint_eq(fcm[150], 0x5A);
    ck_assert_uint_eq(flash_idx, 150);
}
END_TEST

/* col != 0 and len > col: exactly len bytes are copied, starting at col,
 * not len - col bytes as in the pre-fix loop. */
START_TEST(test_write_len_gt_col)
{
    uint8_t data[100];

    fill(data, sizeof(data), 0x33);
    flash_idx = 40;

    hal_flash_write_bytes(data, sizeof(data));

    ck_assert_int_eq(memcmp(fcm + 40, data, sizeof(data)), 0);
    ck_assert_uint_eq(fcm[39], 0x5A);
    ck_assert_uint_eq(fcm[140], 0x5A);
    ck_assert_uint_eq(flash_idx, 140);
}
END_TEST

/* A one-to-three byte tail must not be copied as a full word: the
 * pre-fix loop read/wrote a fourth byte past the requested range. */
START_TEST(test_write_tail_no_word_spill)
{
    uint8_t data[10];

    fill(data, sizeof(data), 0x44);
    flash_idx = 10; /* col not a word boundary either */

    hal_flash_write_bytes(data, sizeof(data));

    ck_assert_int_eq(memcmp(fcm + 10, data, sizeof(data)), 0);
    ck_assert_uint_eq(fcm[20], 0x5A);
    ck_assert_uint_eq(fcm[21], 0x5A);
    ck_assert_uint_eq(flash_idx, 20);
}
END_TEST

/* Column-0 read with a short tail: exactly len bytes out, no word spill. */
START_TEST(test_read_col_zero_tail)
{
    uint8_t data[10];
    size_t i;

    for (i = 0; i < 16; i++)
        fcm[i] = (uint8_t)(0x50 + i);
    memset(data, 0x00, sizeof(data));
    flash_idx = 0;

    hal_flash_read_bytes(data, sizeof(data));

    for (i = 0; i < sizeof(data); i++)
        ck_assert_uint_eq(data[i], fcm[i]);
    ck_assert_uint_eq(fcm[10], 0x5A); /* untouched */
    ck_assert_uint_eq(flash_idx, 10);
}
END_TEST

/* Read with col != 0 and len <= col: the pre-fix loop ran zero times and
 * left the caller's buffer unchanged. */
START_TEST(test_read_len_le_col)
{
    uint8_t data[20];
    size_t i;

    for (i = 0; i < 20; i++)
        fcm[100 + i] = (uint8_t)(0x70 + i);
    memset(data, 0x00, sizeof(data));
    flash_idx = 100;

    hal_flash_read_bytes(data, sizeof(data));

    ck_assert_int_eq(memcmp(data, fcm + 100, sizeof(data)), 0);
    ck_assert_uint_eq(flash_idx, 120);
}
END_TEST

/* Read with col != 0 and len > col: exactly len bytes out. */
START_TEST(test_read_len_gt_col)
{
    uint8_t data[60];
    size_t i;

    for (i = 0; i < 64; i++)
        fcm[48 + i] = (uint8_t)(0x80 + i);
    memset(data, 0x00, sizeof(data));
    flash_idx = 48;

    hal_flash_read_bytes(data, sizeof(data));

    ck_assert_int_eq(memcmp(data, fcm + 48, sizeof(data)), 0);
    ck_assert_uint_eq(flash_idx, 108);
}
END_TEST

Suite *p1021_fcm_suite(void)
{
    Suite *s = suite_create("p1021-fcm-bytes");
    TCase *tc = tcase_create("p1021-fcm-bytes");

    tcase_add_checked_fixture(tc, setup, teardown);
    tcase_add_test(tc, test_write_col_zero);
    tcase_add_test(tc, test_write_len_le_col);
    tcase_add_test(tc, test_write_len_gt_col);
    tcase_add_test(tc, test_write_tail_no_word_spill);
    tcase_add_test(tc, test_read_col_zero_tail);
    tcase_add_test(tc, test_read_len_le_col);
    tcase_add_test(tc, test_read_len_gt_col);

    suite_add_tcase(s, tc);
    return s;
}

int main(void)
{
    int fails;
    Suite *s = p1021_fcm_suite();
    SRunner *sr = srunner_create(s);

    srunner_run_all(sr, CK_NORMAL);
    fails = srunner_ntests_failed(sr);
    srunner_free(sr);

    return fails;
}
