/* unit-imx8qm-usdhc-shim.c
 *
 * Locks down the uSDHC-to-SDHCI register shim in hal/imx8qm.c.
 *
 * src/sdhci.c is written against the Cadence register naming (the SD standard
 * register set at 0x200 + the standard offset) and reaches the controller only
 * through sdhci_reg_read/sdhci_reg_write. i.MX uSDHC is the little-endian
 * descendant of the QorIQ eSDHC and is close to, but not the same as, standard
 * SDHCI, so hal/imx8qm.c translates. Every translation is a place the boot can
 * fail silently on hardware, and none of it is exercised by a build, so it is
 * pinned here instead.
 *
 * The shim functions are extracted verbatim from hal/imx8qm.c
 * (imx8qm_usdhc_extract.h, generated by the Makefile) and driven against an
 * emulated register file, so the code under test is the shipped code rather
 * than a transcription of it.
 *
 * Copyright (C) 2026 wolfSSL Inc.
 *
 * This file is part of wolfBoot.
 *
 * wolfBoot is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfBoot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 */

#include <check.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define TARGET_imx8qm
#define ARCH_AARCH64
#define DISK_SDCARD

#include "imx8qm.h"
#include "sdhci.h"

/* Emulated uSDHC register block, in place of 0x5B020000. */
static uint32_t g_usdhc[0x100];
#define IMX8QM_USDHC_BASE ((uintptr_t)g_usdhc)

#define REG(off) g_usdhc[(off) / 4]

/* Order log: writing CMD_XFR_TYP is what starts a command on uSDHC, so
 * MIX_CTRL has to be written first. Every register write is recorded so the
 * order can be asserted. */
#define WLOG_MAX 64
static uint32_t g_wlog[WLOG_MAX];
static int g_wlog_n;

static inline uint32_t rd32(uintptr_t a) { return *(volatile uint32_t*)a; }
static inline void wr32(uintptr_t a, uint32_t v)
{
    if (g_wlog_n < WLOG_MAX)
        g_wlog[g_wlog_n++] = (uint32_t)(a - (uintptr_t)g_usdhc);
    *(volatile uint32_t*)a = v;
}

/* The shim's bounded waits poll a register while a deadline runs down. The
 * emulated controller clears its self-clearing bits after a couple of polls,
 * the way real hardware does, so the reset and clock-settle paths complete
 * instead of timing out. */
static int g_ticks;
static uint64_t timer_deadline_us(uint32_t us) { (void)us; g_ticks = 0; return 0; }
static int timer_expired(uint64_t deadline)
{
    (void)deadline;
    if (++g_ticks == 2) {
        REG(USDHC_SYS_CTRL) &= ~(uint32_t)(USDHC_SYS_RSTA | USDHC_SYS_INITA);
        REG(USDHC_PRES_STATE) |= USDHC_PRES_SDSTB;
    }
    return g_ticks > 200;
}

static int g_printf_calls;
#define wolfBoot_printf(...) do { g_printf_calls++; } while (0)

#include "imx8qm_usdhc_extract.h"

#undef wolfBoot_printf

/* Standard-SDHCI offsets as the generic driver addresses them. */
#define SRS(n)  (CADENCE_SRS_OFFSET + (n))

static void setup(void)
{
    memset(g_usdhc, 0, sizeof(g_usdhc));
    g_wlog_n = 0;
    g_ticks = 0;
    g_printf_calls = 0;
    srs10_shadow = 0;
    srs15_shadow = 0;
    usdhc_achieved_clk_khz = IMX8QM_USDHC_PERCLK_HZ / 1000;
}

static void teardown(void) { }

/* --------------------------------------------------------------------------
 * The command register split. Standard SDHCI keeps transfer mode in the low
 * half of 0x0C; uSDHC keeps it in MIX_CTRL and only the command half at 0x0C.
 * -------------------------------------------------------------------------- */
START_TEST(test_cmd_split_and_order)
{
    uint32_t cmd;

    /* Pre-set a tuning bit that lives above the transfer-mode field: the shim
     * must preserve it, since standard SDHCI has no equivalent to lose it
     * from. */
    REG(USDHC_MIX_CTRL) = (1U << 23);

    /* CMD18 READ_MULTIPLE_BLOCK the way src/sdhci.c builds it. */
    cmd = (18U << SDHCI_SRS03_CIDX_SHIFT) | SDHCI_SRS03_DPS |
          SDHCI_SRS03_BCE | SDHCI_SRS03_RECE | SDHCI_SRS03_RID |
          SDHCI_SRS03_RESP_48 | SDHCI_SRS03_CRCCE | SDHCI_SRS03_CICE |
          SDHCI_SRS03_DTDS | SDHCI_SRS03_MSBS;
    sdhci_reg_write(SRS(0x0C), cmd);

    /* Transfer-mode half landed in MIX_CTRL... */
    ck_assert_uint_eq(REG(USDHC_MIX_CTRL) & USDHC_MIX_CTRL_XFER_MASK,
                      cmd & USDHC_MIX_CTRL_XFER_MASK);
    /* ...the tuning bit above it survived... */
    ck_assert_uint_eq(REG(USDHC_MIX_CTRL) & (1U << 23), (1U << 23));
    /* ...and no transfer-mode bits leaked into the command register. */
    ck_assert_uint_eq(REG(USDHC_CMD_XFR_TYP) & 0xFFFFU, 0);
    ck_assert_uint_eq(REG(USDHC_CMD_XFR_TYP) & SDHCI_SRS03_CIDX_MASK,
                      18U << SDHCI_SRS03_CIDX_SHIFT);

    /* MIX_CTRL must be written before CMD_XFR_TYP, which triggers the
     * command: the other order runs the command with the previous transfer
     * mode. */
    ck_assert_int_ge(g_wlog_n, 2);
    ck_assert_uint_eq(g_wlog[0], USDHC_MIX_CTRL);
    ck_assert_uint_eq(g_wlog[1], USDHC_CMD_XFR_TYP);
}
END_TEST

/* The Cadence response-error-check and response-interrupt-disable bits occupy
 * the same two bits as the response type, so a data command arrives asking for
 * "48-bit with busy". Every SD data command is R1, not R1b, and a busy check
 * would wait on DAT0 for a card that never drives it. */
START_TEST(test_data_cmd_busy_downgrade)
{
    uint32_t cmd = (18U << SDHCI_SRS03_CIDX_SHIFT) | SDHCI_SRS03_DPS |
          SDHCI_SRS03_RECE | SDHCI_SRS03_RID | SDHCI_SRS03_RESP_48;

    sdhci_reg_write(SRS(0x0C), cmd);
    ck_assert_uint_eq(REG(USDHC_CMD_XFR_TYP) & USDHC_XFR_RSPTYP_MASK,
                      USDHC_XFR_RSPTYP_48);
}
END_TEST

/* ...but a genuine R1b command with no data must keep the busy check, or the
 * driver stops waiting for the card to finish. */
START_TEST(test_nondata_r1b_keeps_busy)
{
    uint32_t cmd = (12U << SDHCI_SRS03_CIDX_SHIFT) |
          SDHCI_SRS03_RESP_48B | SDHCI_SRS03_CRCCE | SDHCI_SRS03_CICE;

    sdhci_reg_write(SRS(0x0C), cmd);
    ck_assert_uint_eq(REG(USDHC_CMD_XFR_TYP) & USDHC_XFR_RSPTYP_MASK,
                      USDHC_XFR_RSPTYP_48B);
}
END_TEST

/* --------------------------------------------------------------------------
 * Host Control 1. uSDHC encodes bus width as a 2-bit field and has no bus
 * power or bus voltage fields at all, so the driver's read-modify-write cycles
 * only work if the shim round-trips both.
 * -------------------------------------------------------------------------- */
START_TEST(test_bus_width_roundtrip)
{
    sdhci_reg_write(SRS(0x28), SDHCI_SRS10_DTW);
    ck_assert_uint_eq(REG(USDHC_PROT_CTRL) & USDHC_PROT_DTW_MASK,
                      USDHC_PROT_DTW_4BIT);
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x28)) & SDHCI_SRS10_DTW,
                      SDHCI_SRS10_DTW);
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x28)) & SDHCI_SRS10_EDTW, 0);

    sdhci_reg_write(SRS(0x28), SDHCI_SRS10_EDTW);
    ck_assert_uint_eq(REG(USDHC_PROT_CTRL) & USDHC_PROT_DTW_MASK,
                      USDHC_PROT_DTW_8BIT);
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x28)) & SDHCI_SRS10_EDTW,
                      SDHCI_SRS10_EDTW);
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x28)) & SDHCI_SRS10_DTW, 0);

    sdhci_reg_write(SRS(0x28), 0);
    ck_assert_uint_eq(REG(USDHC_PROT_CTRL) & USDHC_PROT_DTW_MASK,
                      USDHC_PROT_DTW_1BIT);
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x28)) &
                      (SDHCI_SRS10_DTW | SDHCI_SRS10_EDTW), 0);
}
END_TEST

/* sdhci_set_power() clears bus power, then reads back and sets voltage. uSDHC
 * has no such register, so a shadow has to carry it. */
START_TEST(test_bus_power_shadow_roundtrip)
{
    uint32_t reg;

    sdhci_reg_write(SRS(0x28), SDHCI_SRS10_BP | SDHCI_SRS10_BVS_3_3V |
                               SDHCI_SRS10_DTW);
    reg = sdhci_reg_read(SRS(0x28));
    ck_assert_uint_eq(reg & SDHCI_SRS10_BP, SDHCI_SRS10_BP);
    ck_assert_uint_eq(reg & SDHCI_SRS10_BVS_MASK, SDHCI_SRS10_BVS_3_3V);
    ck_assert_uint_eq(reg & SDHCI_SRS10_DTW, SDHCI_SRS10_DTW);
}
END_TEST

/* --------------------------------------------------------------------------
 * Clock control. The reset and data-timeout fields line up with standard
 * SDHCI and pass through; the divider does not, and is owned by
 * sdhci_platform_set_clock. A standard divisor write must not clobber it.
 * -------------------------------------------------------------------------- */
START_TEST(test_clock_ctrl_preserves_divider)
{
    uint32_t before;

    sdhci_platform_set_clock(400, 0);
    before = REG(USDHC_SYS_CTRL) &
             (USDHC_SYS_DVS_MASK | USDHC_SYS_SDCLKFS_MASK);
    ck_assert_uint_ne(before, 0);

    /* What sdhci_set_clock() writes once its own divider maths has run. */
    sdhci_reg_write(SRS(0x2C), SDHCI_SRS11_ICE | (0xFFU << 8) |
                               (0xEU << SDHCI_SRS11_DTCV_SHIFT));

    ck_assert_uint_eq(REG(USDHC_SYS_CTRL) &
                      (USDHC_SYS_DVS_MASK | USDHC_SYS_SDCLKFS_MASK), before);
    ck_assert_uint_eq(REG(USDHC_SYS_CTRL) & USDHC_SYS_DTOCV_MASK,
                      0xEU << USDHC_SYS_DTOCV_SHIFT);
}
END_TEST

/* uSDHC gates its clocks automatically and has no internal-clock-enable or
 * clock-stable bit. The driver spins on both, so the shim must report them
 * satisfied or the boot hangs. Reset bits still come from hardware. */
START_TEST(test_clock_ctrl_readback)
{
    uint32_t reg = sdhci_reg_read(SRS(0x2C));

    ck_assert_uint_eq(reg & SDHCI_SRS11_ICE, SDHCI_SRS11_ICE);
    ck_assert_uint_eq(reg & SDHCI_SRS11_ICS, SDHCI_SRS11_ICS);
    ck_assert_uint_eq(reg & SDHCI_SRS11_SDCE, SDHCI_SRS11_SDCE);
    ck_assert_uint_eq(reg & SDHCI_SRS11_RESET_ALL, 0);

    REG(USDHC_SYS_CTRL) |= USDHC_SYS_RSTA;
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x2C)) & SDHCI_SRS11_RESET_ALL,
                      SDHCI_SRS11_RESET_ALL);
}
END_TEST

/* The reset bits are what sdhci_reset_lines() drives, and it spins until they
 * clear, so they have to reach the hardware. */
START_TEST(test_reset_bits_pass_through)
{
    sdhci_reg_write(SRS(0x2C), SDHCI_SRS11_RESET_DAT_CMD);
    ck_assert_uint_eq(REG(USDHC_SYS_CTRL) &
                      (USDHC_SYS_RSTC | USDHC_SYS_RSTD),
                      USDHC_SYS_RSTC | USDHC_SYS_RSTD);
}
END_TEST

/* The divider must land at or below the requested rate - never above, which
 * would overclock the card during identification. */
START_TEST(test_set_clock_divider)
{
    uint32_t pre, dvs, achieved;

    ck_assert_uint_ne(sdhci_platform_set_clock(400, 0), 0);
    pre = (REG(USDHC_SYS_CTRL) & USDHC_SYS_SDCLKFS_MASK)
            >> USDHC_SYS_SDCLKFS_SHIFT;
    dvs = ((REG(USDHC_SYS_CTRL) & USDHC_SYS_DVS_MASK)
            >> USDHC_SYS_DVS_SHIFT) + 1;
    pre = (pre == 0) ? 1 : pre * 2;
    achieved = (IMX8QM_USDHC_PERCLK_HZ / (pre * dvs)) / 1000;
    ck_assert_uint_le(achieved, 400);

    /* The achieved rate is reported back as the base clock, so the generic
     * driver's own divider computation settles on 1. */
    ck_assert_uint_eq(sdhci_platform_set_clock(25000, 0), usdhc_achieved_clk_khz);
    ck_assert_uint_le(usdhc_achieved_clk_khz, 25000);
}
END_TEST

/* --------------------------------------------------------------------------
 * Interrupt status. uSDHC has no error-interrupt summary bit, and its DMA
 * error sits at bit 28 rather than the standard bit 25.
 * -------------------------------------------------------------------------- */
START_TEST(test_error_summary_synthesized)
{
    /* sdhci_send_cmd_internal() polls for CC | TC | EINT and reports an error
     * only when EINT is set. Without synthesis a command timeout would look
     * like a hang instead of a failure. */
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x30)) & SDHCI_SRS12_EINT, 0);

    REG(USDHC_INT_STATUS) = SDHCI_SRS12_ECT;   /* command timeout */
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x30)) & SDHCI_SRS12_EINT,
                      SDHCI_SRS12_EINT);

    /* A normal-status bit alone must not raise the error summary. */
    REG(USDHC_INT_STATUS) = SDHCI_SRS12_CC;
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x30)) & SDHCI_SRS12_EINT, 0);
}
END_TEST

START_TEST(test_dma_error_bit_remap)
{
    REG(USDHC_INT_STATUS) = (1U << 28);   /* uSDHC DMA error */
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x30)) & SDHCI_SRS12_EADMA,
                      SDHCI_SRS12_EADMA);
    /* The uSDHC-only position must not also be presented raw. */
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x30)) & (1U << 28), 0);

    /* Write-1-to-clear has to reach the bit the hardware actually uses. */
    g_usdhc[USDHC_INT_STATUS / 4] = 0;
    sdhci_reg_write(SRS(0x30), SDHCI_SRS12_EADMA);
    ck_assert_uint_eq(REG(USDHC_INT_STATUS) & (1U << 28), (1U << 28));
    /* The synthesized summary bit is not a real register bit. */
    ck_assert_uint_eq(REG(USDHC_INT_STATUS) & SDHCI_SRS12_EINT, 0);
}
END_TEST

/* On uSDHC a status bit does not latch unless its enable is set, so the
 * uSDHC-only error enables must be added to the driver's mask. */
START_TEST(test_status_enable_adds_usdhc_errors)
{
    sdhci_reg_write(SRS(0x34), SDHCI_SRS12_ERR_STAT | SDHCI_SRS12_CC);
    ck_assert_uint_eq(REG(USDHC_INT_STATUS_EN) & (1U << 28), (1U << 28));
    ck_assert_uint_eq(REG(USDHC_INT_STATUS_EN) & (1U << 26), (1U << 26));
}
END_TEST

/* --------------------------------------------------------------------------
 * Present state and capabilities.
 * -------------------------------------------------------------------------- */
START_TEST(test_present_state_dat0_remap)
{
    /* sdhci_wait_busy() spins on DAT0 level. uSDHC reports it in the DLSL
     * field at bit 24, not at the standard bit 20 - so without the remap the
     * wait never sees the card go ready. */
    REG(USDHC_PRES_STATE) = USDHC_PRES_DLSL_DAT0;
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x24)) & SDHCI_SRS09_DAT0_LVL,
                      SDHCI_SRS09_DAT0_LVL);

    REG(USDHC_PRES_STATE) = 0;
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x24)) & SDHCI_SRS09_DAT0_LVL, 0);

    /* Card state stable has no uSDHC bit; report it satisfied. */
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x24)) & SDHCI_SRS09_CSS,
                      SDHCI_SRS09_CSS);

    /* Command inhibit is at the standard position and must pass through. */
    REG(USDHC_PRES_STATE) = USDHC_PRES_CIHB;
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x24)) & SDHCI_SRS09_CICMD,
                      SDHCI_SRS09_CICMD);
}
END_TEST

START_TEST(test_capabilities_synthesized)
{
    uint32_t cap;

    /* uSDHC leaves the timeout-clock and base-clock fields at zero, which
     * sdhci_set_timeout() rejects outright and sdhci_set_clock() treats as
     * "no usable base clock". */
    REG(USDHC_HOST_CTRL_CAP) = USDHC_CAP_VS33 | USDHC_CAP_VS18;
    cap = sdhci_reg_read(SRS(0x40));

    ck_assert_uint_ne(cap & SDHCI_SRS16_TCF_MASK, 0);
    ck_assert_uint_eq(cap & SDHCI_SRS16_TCU, SDHCI_SRS16_TCU);
    ck_assert_uint_ne(cap & SDHCI_SRS16_BCSDCLK_MASK, 0);
    /* Voltage support is already at the standard positions. */
    ck_assert_uint_eq(cap & SDHCI_SRS16_VS33, SDHCI_SRS16_VS33);
    ck_assert_uint_eq(cap & SDHCI_SRS16_VS18, SDHCI_SRS16_VS18);
    ck_assert_uint_eq(cap & SDHCI_SRS16_VS30, 0);
    /* PIO only: 64-bit addressing must not be advertised. */
    ck_assert_uint_eq(cap & SDHCI_SRS16_A64S, 0);
}
END_TEST

/* uSDHC uses bit 12 as part of the block size, where standard SDHCI starts the
 * SDMA buffer-boundary field. Letting a boundary bit through would silently
 * change the block size. */
START_TEST(test_block_attr_masks_dma_boundary)
{
    sdhci_reg_write(SRS(0x04), (8U << SDHCI_SRS01_BCCT_SHIFT) |
                               SDHCI_SRS01_DMA_BUFF_512KB | 512U);
    ck_assert_uint_eq(REG(USDHC_BLK_ATT) & 0x1FFFU, 512U);
    ck_assert_uint_eq(REG(USDHC_BLK_ATT) >> 16, 8U);
}
END_TEST

/* The Cadence host-register range has no uSDHC equivalent. The driver spins on
 * the PHY handshake, so a read has to answer it. */
START_TEST(test_hrs_region)
{
    ck_assert_uint_eq(sdhci_reg_read(SDHCI_HRS04), SDHCI_HRS04_UIS_ACK);
    ck_assert_uint_eq(sdhci_reg_read(SDHCI_HRS06), 0);

    /* The one host register the driver writes is the software reset. */
    sdhci_reg_write(SDHCI_HRS00, SDHCI_HRS00_SWR);
    ck_assert_uint_eq(REG(USDHC_SYS_CTRL) & USDHC_SYS_RSTA, USDHC_SYS_RSTA);
}
END_TEST

/* platform_init has to leave the data port little-endian and the watermark at
 * a full block, or the generic driver's PIO loop sees one Buffer Read Ready
 * every 32 bytes instead of one per block. */
START_TEST(test_platform_init)
{
    sdhci_platform_init();

    ck_assert_uint_eq(REG(USDHC_PROT_CTRL) & USDHC_PROT_EMODE_MASK,
                      USDHC_PROT_EMODE_LE);
    ck_assert_uint_eq(REG(USDHC_PROT_CTRL) & USDHC_PROT_D3CD, 0);
    ck_assert_uint_eq((REG(USDHC_WTMK_LVL) >> USDHC_WTMK_RD_SHIFT) & 0xFF,
                      USDHC_WTMK_BLOCK_WORDS);
    ck_assert_uint_eq((REG(USDHC_WTMK_LVL) >> USDHC_WTMK_WR_SHIFT) & 0xFF,
                      USDHC_WTMK_BLOCK_WORDS);
}
END_TEST

/* Registers with no translation must reach the hardware untouched: the
 * argument register, the response registers and the data port carry the
 * actual transfer. */
START_TEST(test_passthrough_registers)
{
    sdhci_reg_write(SRS(0x08), 0xAABBCCDDU);
    ck_assert_uint_eq(REG(USDHC_CMD_ARG), 0xAABBCCDDU);

    REG(USDHC_CMD_RSP0) = 0x12345678U;
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x10)), 0x12345678U);

    REG(USDHC_DATA_BUFF_ACC_PORT) = 0xDEADBEEFU;
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x20)), 0xDEADBEEFU);
}
END_TEST

START_TEST(test_tuning_error_reaches_summary)
{
    /* TNE is a uSDHC-only bit with no standard SDHCI equivalent, so it is
     * stripped on read. It must still raise the synthesized error summary:
     * left out, a latched tuning error is invisible to the generic driver,
     * which then waits on a transfer that will never complete. */
    REG(USDHC_INT_STATUS) = USDHC_INT_TNE;
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x30)) & SDHCI_SRS12_EINT,
                      SDHCI_SRS12_EINT);
    /* ...while the uSDHC-only bit itself stays hidden. */
    ck_assert_uint_eq(sdhci_reg_read(SRS(0x30)) & USDHC_INT_TNE, 0);
}
END_TEST

START_TEST(test_tuning_error_cleared_via_summary)
{
    /* The driver can only ever write back bits it can see, so clearing has to
     * work through the synthesized summary bit. Otherwise TNE latches and
     * holds the summary asserted for the rest of the boot. */
    REG(USDHC_INT_STATUS) = USDHC_INT_TNE | SDHCI_SRS12_ECT;
    sdhci_reg_write(SRS(0x30), SDHCI_SRS12_EINT | SDHCI_SRS12_ECT);
    ck_assert_uint_eq(REG(USDHC_INT_STATUS) & USDHC_INT_TNE, USDHC_INT_TNE);
}
END_TEST

Suite *imx8qm_usdhc_suite(void)
{
    Suite *s = suite_create("imx8qm-usdhc-shim");
    TCase *tc = tcase_create("imx8qm-usdhc-shim");

    tcase_add_checked_fixture(tc, setup, teardown);
    tcase_add_test(tc, test_cmd_split_and_order);
    tcase_add_test(tc, test_data_cmd_busy_downgrade);
    tcase_add_test(tc, test_nondata_r1b_keeps_busy);
    tcase_add_test(tc, test_bus_width_roundtrip);
    tcase_add_test(tc, test_bus_power_shadow_roundtrip);
    tcase_add_test(tc, test_clock_ctrl_preserves_divider);
    tcase_add_test(tc, test_clock_ctrl_readback);
    tcase_add_test(tc, test_reset_bits_pass_through);
    tcase_add_test(tc, test_set_clock_divider);
    tcase_add_test(tc, test_error_summary_synthesized);
    tcase_add_test(tc, test_dma_error_bit_remap);
    tcase_add_test(tc, test_tuning_error_reaches_summary);
    tcase_add_test(tc, test_tuning_error_cleared_via_summary);
    tcase_add_test(tc, test_status_enable_adds_usdhc_errors);
    tcase_add_test(tc, test_present_state_dat0_remap);
    tcase_add_test(tc, test_capabilities_synthesized);
    tcase_add_test(tc, test_block_attr_masks_dma_boundary);
    tcase_add_test(tc, test_hrs_region);
    tcase_add_test(tc, test_platform_init);
    tcase_add_test(tc, test_passthrough_registers);

    suite_add_tcase(s, tc);
    return s;
}

int main(void)
{
    int fails;
    Suite *s = imx8qm_usdhc_suite();
    SRunner *sr = srunner_create(s);

    srunner_run_all(sr, CK_NORMAL);
    fails = srunner_ntests_failed(sr);
    srunner_free(sr);

    return fails;
}
