ARCH_FLASH_OFFSET=0x08000000
LSCRIPT_IN=hal/stm32wb.ld

CFLAGS+=-DWHAL_CFG_CLOCK_API_MAPPING_STM32WB_PLL
CFLAGS+=-DWHAL_CFG_FLASH_API_MAPPING_STM32WB
CFLAGS+=-DWHAL_CFG_GPIO_API_MAPPING_STM32WB
CFLAGS+=-DWHAL_CFG_UART_API_MAPPING_STM32WB

WOLFHAL_OBJS+=$(WOLFHAL_ROOT)/src/clock/stm32wb_rcc.o
WOLFHAL_OBJS+=$(WOLFHAL_ROOT)/src/flash/stm32wb_flash.o
ifeq ($(DEBUG_UART),1)
  WOLFHAL_OBJS+=$(WOLFHAL_ROOT)/src/gpio/stm32wb_gpio.o
  WOLFHAL_OBJS+=$(WOLFHAL_ROOT)/src/uart/stm32wb_uart.o
endif

OBJS+=$(WOLFHAL_OBJS)
APP_OBJS+=$(WOLFHAL_OBJS)

ifeq ($(RAM_CODE),1)
  WOLFHAL_FLASH_EXCLUDE_TEXT=*(EXCLUDE_FILE(*stm32wb_flash.o) .text*)
  WOLFHAL_FLASH_EXCLUDE_RODATA=*(EXCLUDE_FILE(*stm32wb_flash.o) .rodata*)
  WOLFHAL_FLASH_RAM_SECTIONS=*stm32wb_flash.o(.text* .rodata*)
endif
