#!/bin/sh
#
# gen_mpfs_libero_stub.sh -- generate a CI compile-only Libero settings stub.
#
# Defines every LIBERO_SETTING_* symbol referenced by the PolarFire SoC
# MPFS250 HAL to 0, so GitHub Actions can compile-check the MPFS_DDR_INIT
# code path with config/examples/polarfire_mpfs250_m.config (which leaves
# LIBERO_FPGA_CONFIG_DIR unset by default).
#
# This is NOT a board configuration: the values are all zeros and will NOT
# produce a runnable bootloader.  Real boards must point
# LIBERO_FPGA_CONFIG_DIR at the actual Libero / HSS-generated
# fpga_design_config directory (e.g.
#   $HSS/build/boards/mpfs-video-kit/fpga_design_config
# for the MPFS250T Video Kit).
#
# Maintained by wolfSSL.  Generated, not committed (see .gitignore); the
# symbol list is derived from the HAL sources, so it stays in sync
# automatically.
#
# Usage: tools/ci/gen_mpfs_libero_stub.sh <output-dir>
#   Writes <output-dir>/fpga_design_config.h
#
set -e

OUT="${1:?usage: $0 <output-dir>}"
SRCS="hal/mpfs250.c hal/mpfs250.h hal/mpfs250_ddr.c"

# Settings used as a loop upper bound ("i < LIBERO_SETTING_X") must be >= 1,
# otherwise "unsigned i < 0" trips -Werror=type-limits.  Everything else is 0.
# (The build is compile-only, so the loop count value is irrelevant.)
BOUNDS=$(grep -ohE "<=?[[:space:]]*LIBERO_SETTING_[A-Z0-9_]+" $SRCS \
    | grep -oE "LIBERO_SETTING_[A-Z0-9_]+" | sort -u)

mkdir -p "$OUT"
{
    echo "/* AUTO-GENERATED by tools/ci/gen_mpfs_libero_stub.sh -- do not edit."
    echo " * CI compile-only stub; NOT a runnable board config. */"
    echo "#ifndef MPFS_LIBERO_CI_STUB_H"
    echo "#define MPFS_LIBERO_CI_STUB_H"
    grep -ohE "LIBERO_SETTING_[A-Z0-9_]+" $SRCS | sort -u | while read -r sym; do
        case " $BOUNDS " in
            *" $sym "*) echo "#define $sym 1U" ;;
            *)          echo "#define $sym 0"  ;;
        esac
    done
    echo "#endif /* MPFS_LIBERO_CI_STUB_H */"
} > "$OUT/fpga_design_config.h"

echo "Generated $OUT/fpga_design_config.h ($(grep -c '^#define' "$OUT/fpga_design_config.h") settings)"
