#Defaults, used by CI
ifeq ($(ARCH),)
  ARCH?=ARM
  TARGET?=stm32f4
  SIGN?=ED25519
  HASH?=SHA256
  MCUXPRESSO?=$(HOME)/src/FRDM-K64F
  MCUXPRESSO_CPU=MK64FN1M0VLL12
  MCUXPRESSO_DRIVERS?=$(MCUXPRESSO)/devices/MK64F12
  MCUXPRESSO_CMSIS?=$(MCUXPRESSO)/CMSIS
  FREEDOM_E_SDK?=$(HOME)/src/freedom-e-sdk
  STM32CUBE?=$(HOME)/STM32Cube/Repository/STM32Cube_FW_WB_V1.3.0
  DEBUG?=0
  VTOR?=1
  CORTEX_M0?=0
  NO_ASM?=0
  EXT_FLASH?=0
  SPI_FLASH?=0
  ALLOW_DOWNGRADE?=0
  NVM_FLASH_WRITEONCE?=0
  WOLFBOOT_VERSION?=0
  V?=0
  SPMATH?=1
  RAM_CODE?=0
  DUALBANK_SWAP=0
  IMAGE_HEADER_SIZE?=256
  PKA=1
  WOLFTPM=0
  WOLFBOOT_PARTITION_SIZE?=0x20000
  WOLFBOOT_SECTOR_SIZE?=0x20000
  WOLFBOOT_PARTITION_BOOT_ADDRESS?=0x20000
  WOLFBOOT_PARTITION_UPDATE_ADDRESS?=0x40000
  WOLFBOOT_PARTITION_SWAP_ADDRESS?=0x60000
endif


CONFIG_VARS:= ARCH TARGET SIGN HASH MCUXPRESSO MCUXPRESSO_CPU MCUXPRESSO_DRIVERS \
	MCUXPRESSO_CMSIS FREEDOM_E_SDK STM32CUBE DEBUG VTOR CORTEX_M0 NO_ASM EXT_FLASH \
	SPI_FLASH ALLOW_DOWNGRADE NVM_FLASH_WRITEONCE WOLFBOOT_VERSION V \
	SPMATH RAM_CODE DUALBANK_SWAP IMAGE_HEADER_SIZE PKA WOLFTPM \
	WOLFBOOT_PARTITION_SIZE WOLFBOOT_SECTOR_SIZE  \
	WOLFBOOT_PARTITION_BOOT_ADDRESS WOLFBOOT_PARTITION_UPDATE_ADDRESS \
	WOLFBOOT_PARTITION_SWAP_ADDRESS
