name: Wolfboot Reusable Build Workflow for west-based MCUXpresso SDK

on:

  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      config-file:
        required: true
        type: string
      board-name:
        required: true
        type: string
      make-args:
        required: false
        type: string

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wolfssl/wolfboot-ci-arm:v0.9.4
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/checkout@main
        with:
          repository: nxp-mcuxpresso/CMSIS_5
          path: CMSIS_5

      - name: Trust workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Cache MCUXpresso SDK
        id: cache-mcuxpresso
        uses: actions/cache@v4
        with:
          path: |
            mcuxpresso-sdk
            venv
          key: mcuxpresso-sdk-${{inputs.board-name}}-${{hashFiles('.github/workflows/test-build-mcux-sdk-manifests.yml')}}

      - name: Setup MCUXpresso SDK
        if: steps.cache-mcuxpresso.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install west
          west init -m https://github.com/nxp-mcuxpresso/mcuxsdk-manifests.git mcuxpresso-sdk
          cd mcuxpresso-sdk
          sed -i '/se_hostlib\|emwin/d' manifests/boards/${{inputs.board-name}}.yml
          west update_board --set board ${{inputs.board-name}}

      - name: make distclean
        run: |
          make distclean

      - name: Select config
        run: |
          cp ${{inputs.config-file}} .config && make include/target.h

      - name: Build tools
        run: |
          make -C tools/keytools && make -C tools/bin-assemble

      - name: Build wolfboot
        run: |
          make MCUXSDK=1 MCUXPRESSO="$GITHUB_WORKSPACE/mcuxpresso-sdk/mcuxsdk" MCUXPRESSO_CMSIS="$GITHUB_WORKSPACE/CMSIS_5/CMSIS" ${{inputs.make-args}} V=1
