name: Simulator self-update and self-header tests

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  self_update_simulator_test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wolfssl/wolfboot-ci-sim:v1.0
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Trust workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Run self-update test (internal flash)
        run: |
          cp config/examples/sim-self-update.config .config
          make test-sim-self-update

      - name: Run self-update test (external flash)
        run: |
          make clean
          cp config/examples/sim-self-update-ext.config .config
          make test-sim-self-update-ext

      - name: Run self-header verification test (internal flash)
        run: |
          make clean
          cp config/examples/sim-self-header.config .config
          make test-sim-self-header-verify

      - name: Run self-header verification test (external flash)
        run: |
          make clean
          cp config/examples/sim-self-header-ext.config .config
          make test-sim-self-header-ext-verify
