name: Wolfboot Reusable Build Workflow

on:

  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      config-file:
        required: true
        type: string
      make-args:
        required: false
        type: string

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wolfssl/wolfboot-ci-arm:v1.0
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Trust workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install Clang
        if: inputs.arch == 'arm' || inputs.arch == 'ARM'
        run: |
          sudo apt-get install -y clang

      - name: make clean
        run: |
          make distclean

      - name: Select config
        run: |
          cp ${{inputs.config-file}} .config

      - name: Build tools
        run: |
          make -C tools/keytools && make -C tools/bin-assemble

      - name: Build wolfboot
        run: |
          make ${{inputs.make-args}}

      - name: Rebuild wolfboot with Clang
        if: inputs.arch == 'arm' || inputs.arch == 'ARM'
        run: |
          make distclean
          cp ${{inputs.config-file}} .config
          make -C tools/keytools && make -C tools/bin-assemble
          make USE_CLANG=1 USE_GCC=0 ${{inputs.make-args}}
